package com.taxiappclone.common.model

data class MyRides(
    val accept_time: String,
    val arrived_time: String,
    val cancel_time: String,
    val distance_travelled: String,
    val driver_id: String,
    val driver_location: String,
    val driver_rating: String,
    val driver_review: String,
    val dropoff_address: String,
    val dropoff_location: String,
    val end_time: String,
    val fare: String,
    val fare_details: String,
    val fare_status: String,
    val payment_status: String,
    val payment_type: String,
    val pickup_address: String,
    val pickup_location: String,
    val pickup_time: String,
    val reason: String,
    val reject_time: String,
    val request_time: String,
    val ride_id: String,
    val ride_status: String,
    val rider_id: String,
    val rider_location: String,
    val rider_rating: Any,
    val rider_review: Any,
    val scheduled: String,
    val scheduled_time: String,
    val start_time: String
)